# Generated by Django 5.2.8 on 2025-12-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='target_type',
            field=models.CharField(choices=[('drone', 'Drone'), ('rocket', 'Rocket'), ('plane', 'Plane'), ('helicopter', 'Helicopter'), ('explosion', 'Explosion'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
