# Generated by Django 5.2.8 on 2025-12-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_target_target_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
