# Generated by Django 5.2.8 on 2025-12-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0003_alter_target_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Shelter', max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('capacity', models.IntegerField(default=0, help_text='Capacity (people)')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
