# Generated by Django 5.2.8 on 2025-12-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0005_alter_target_target_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='target_type',
            field=models.CharField(choices=[('drone', 'Drone'), ('rocket', 'Rocket'), ('plane', 'Plane'), ('helicopter', 'Helicopter'), ('bang', 'Bang')], default='bang', max_length=20),
        ),
    ]
