# Generated by Django 5.2.8 on 2025-12-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0006_alter_target_target_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='notifications_sent',
            field=models.BooleanField(default=False),
        ),
    ]
