# Generated by Django 5.2.8 on 2025-12-02 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0007_target_notifications_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='target',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='target',
            name='danger_radius',
            field=models.IntegerField(choices=[(1, '1 km'), (2, '2 km'), (3, '3 km'), (5, '5 km'), (10, '10 km')], default=2, help_text='Danger radius in km'),
        ),
        migrations.AddField(
            model_name='target',
            name='parent_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_reports', to='targets.target'),
        ),
        migrations.AddField(
            model_name='target',
            name='probability',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='target',
            name='report_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='target',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='weighted_score',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='target',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('unconfirmed', 'Unconfirmed'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='target',
            name='target_type',
            field=models.CharField(choices=[('drone', 'Drone'), ('rocket', 'Rocket'), ('plane', 'Plane'), ('helicopter', 'Helicopter'), ('bang', 'Bang')], default='drone', max_length=20),
        ),
    ]
