# Generated by Django 5.2.8 on 2025-12-02 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_telegramlinkcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='trust_rating',
            field=models.FloatField(default=0),
        ),
    ]
